linters-settings:
  nakedret:
    max-func-lines: 0 # Disallow any unnamed return statement
  govet:
    disable:
      # printf: non-constant format string in call to fmt.Errorf (govet)
      # showing up since golangci-lint version 1.60.1
      - printf

linters:
  enable:
    - unused
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - nakedret
    - gofmt
    - rowserrcheck
    - unconvert
    - goimports
    - unparam
