# Docs: https://goreleaser.com
builds:
  - main: ./pgrok/cli
    binary: pgrok
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    wrap_in_directory: false
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      pgrok_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.pgrok.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  skip: true

brews:
  - tap:
      owner: pgrok
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: "Joe Chen"
      email: "jc@unknwon.io"
    homepage: "https://github.com/pgrok/pgrok"
    description: "Poor man's ngrok"
    license: "MIT"
