# Docs: https://goreleaser.com
version: 2
builds:
  - main: ./pgrokd/cli
    binary: pgrokd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    wrap_in_directory: false
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      pgrokd_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.pgrokd.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  disable: true
git:
  tag_sort: semver
