name: Improve documentation
description: Suggest an idea or a patch for documentation
labels: ["📖 documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!

        - Before you file an issue read the [contributing guide](https://github.com/pgrok/pgrok/blob/main/.github/contributing.md).
        - Check to make sure someone hasn't already opened a similar [issue](https://github.com/pgrok/pgrok/issues).
  - type: textarea
    attributes:
      label: What needs to be improved? Please describe
      description: A clear and concise description of what is wrong or missing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why do you think it is important?
      description: A clear and concise explanation of the rationale.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Consent
      options:
        - label: I agree to follow the [Code of Conduct](https://go.dev/conduct)
          required: true
