name: Question
description: Ask us a question.
labels: ["❓question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        - Before you file an issue read the [Flamego's contributing guide](https://github.com/flamego/flamego/blob/main/.github/contributing.md).
        - Check to make sure someone hasn't already opened a similar [issue](https://github.com/pgrok/pgrok/issues).
  - type: textarea
    attributes:
      label: Type out the question
      description: A clear and concise description of your question.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Consent
      options:
        - label: I agree to follow the [Code of Conduct](https://go.dev/conduct)
          required: true
        - label: I understand a satisfying answer is not guaranteed
          required: true
